# Settings
locale:       "ko-KR"
title:        "Sohee Tech Blog" # name of the site
longtitle:    "Sohee Tech Blog"
author:       "Sohee Moon" # name of site's author
email:        "soheetech@gmail.com" # email of site's author
url:          "soheetech.github.io" # root address of the site
baseurl:      "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
rss:          RSS

description: > # description of the site (multiple lines allowed)
  ...

favicon_path: "favicon.ico" # customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}


# Outputting
permalink: /:categories/:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/

timezone: Asia/Seoul
paginate: 10 # amount of posts to show
paginate_path: /page:num/


# Theme
remote_theme : sighingnow/jekyll-gitbook

version:          1.0
gitbook_version:  3.2.3

toc:
  enabled: true
  h_min: 1
  h_max: 3
 
page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true


# Filtering Content
future: true
exclude:
  - _drafts


# Conversion
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
    block:
      line_numbers: true

syntax_highlighter_style: monokai_dark

markdown_ext:     markdown,mkdown,mkdn,mkd,md


# Plugins
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-paginate
  - jekyll-last-modified-at
  
  
# Optional. The default date format, used if none is specified in the tag.
last-modified-at: 
    date-format: '%b %d, %y'
