title: "Sohee Tech Blog" # name of the site
author: "Sohee Moon" # name of site's author
email: "soheetech@gmail.com" # email of site's author
url: "soheetech.github.io" # root address of the site
description: > # description of the site (multiple lines allowed)
  ...


# Serving
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics


# Outputting
permalink: /:categories/:title/
timezone: Asia/Seoul
locale: "ko-KR"


# Theme
remote_theme : riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "Back" # customize text for homepage link in post layout
  date_format: "%Month %d, %Y" # customize how date is formatted
  show_description: false # show blog description in home page


# Where things are
sass:
  style: :compressed


# Filtering Content
futrue: true


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
